// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

//! Data models for LLM-generated flashcards.
//!
//! This module provides the Flashcard struct which represents a generated
//! flashcard before it's converted into an Anki Note.

use serde::{Deserialize, Serialize};

/// Represents the source type of a generated flashcard.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum SourceType {
    /// Generated from plain text
    Text,
    /// Generated from a URL
    Url,
    /// Generated from an audio file
    Audio,
    /// Generated from a video file
    Video,
    /// Generated from a code snippet
    Code,
}

impl Default for SourceType {
    fn default() -> Self {
        SourceType::Text
    }
}

/// Represents a flashcard generated by an LLM.
///
/// This struct holds the raw flashcard data before it's converted
/// into an Anki Note with a specific notetype.
#[derive(Debug, Clone, Default)]
pub struct Flashcard {
    /// The front side of the flashcard (question/prompt)
    pub front: String,
    /// The back side of the flashcard (answer)
    pub back: String,
    /// Tags associated with this flashcard
    pub tags: Vec<String>,
    /// The type of source content this was generated from
    pub source_type: SourceType,
    /// The URL/source URL if generated from a URL
    pub source_url: Option<String>,
}

impl Flashcard {
    /// Create a new flashcard with the given front and back content.
    pub fn new(front: impl Into<String>, back: impl Into<String>) -> Self {
        Flashcard {
            front: front.into(),
            back: back.into(),
            tags: Vec::new(),
            source_type: SourceType::default(),
            source_url: None,
        }
    }

    /// Set the tags for this flashcard.
    pub fn with_tags(mut self, tags: Vec<String>) -> Self {
        self.tags = tags;
        self
    }

    /// Set the source type for this flashcard.
    pub fn with_source_type(mut self, source_type: SourceType) -> Self {
        self.source_type = source_type;
        self
    }

    /// Set the source URL for this flashcard.
    pub fn with_source_url(mut self, url: impl Into<String>) -> Self {
        self.source_url = Some(url.into());
        self
    }

    /// Add a single tag to this flashcard.
    pub fn add_tag(&mut self, tag: impl Into<String>) {
        self.tags.push(tag.into());
    }
}

/// Represents a cloze flashcard with fill-in-the-blank syntax.
///
/// Cloze cards use {{c1::text}} syntax to hide portions of text.
#[derive(Debug, Clone, Default)]
pub struct ClozeFlashcard {
    /// The text containing cloze deletions
    pub text: String,
    /// Extra text to show on the back of the card
    pub back_extra: String,
    /// Tags associated with this flashcard
    pub tags: Vec<String>,
    /// The type of source content this was generated from
    pub source_type: SourceType,
    /// The URL/source URL if generated from a URL
    pub source_url: Option<String>,
}

impl ClozeFlashcard {
    /// Create a new cloze flashcard.
    pub fn new(text: impl Into<String>) -> Self {
        ClozeFlashcard {
            text: text.into(),
            back_extra: String::new(),
            tags: Vec::new(),
            source_type: SourceType::default(),
            source_url: None,
        }
    }

    /// Set the back extra text.
    pub fn with_back_extra(mut self, back_extra: impl Into<String>) -> Self {
        self.back_extra = back_extra.into();
        self
    }

    /// Set the tags for this flashcard.
    pub fn with_tags(mut self, tags: Vec<String>) -> Self {
        self.tags = tags;
        self
    }

    /// Set the source type for this flashcard.
    pub fn with_source_type(mut self, source_type: SourceType) -> Self {
        self.source_type = source_type;
        self
    }

    /// Set the source URL for this flashcard.
    pub fn with_source_url(mut self, url: impl Into<String>) -> Self {
        self.source_url = Some(url.into());
        self
    }
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_flashcard_creation() {
        let card = Flashcard::new("What is Rust?", "A systems programming language.");
        assert_eq!(card.front, "What is Rust?");
        assert_eq!(card.back, "A systems programming language.");
        assert!(card.tags.is_empty());
        assert_eq!(card.source_type, SourceType::Text);
        assert!(card.source_url.is_none());
    }

    #[test]
    fn test_flashcard_with_tags() {
        let card = Flashcard::new("What is Rust?", "A systems programming language.")
            .with_tags(vec!["programming".into(), "rust".into()]);
        assert_eq!(card.tags, vec!["programming", "rust"]);
    }

    #[test]
    fn test_flashcard_with_source() {
        let card = Flashcard::new("What is Rust?", "A systems programming language.")
            .with_source_type(SourceType::Url)
            .with_source_url("https://rust-lang.org");
        assert_eq!(card.source_type, SourceType::Url);
        assert_eq!(card.source_url, Some("https://rust-lang.org".into()));
    }

    #[test]
    fn test_cloze_flashcard_creation() {
        let card = ClozeFlashcard::new("Rust is a {{c1::systems}} programming language.");
        assert!(card.text.contains("{{c1::"));
        assert!(card.back_extra.is_empty());
    }

    #[test]
    fn test_cloze_flashcard_with_back_extra() {
        let card = ClozeFlashcard::new("Rust is a {{c1::systems}} programming language.")
            .with_back_extra("Memory safety without garbage collection.");
        assert_eq!(
            card.back_extra,
            "Memory safety without garbage collection."
        );
    }

    #[test]
    fn test_source_type_default() {
        assert_eq!(SourceType::default(), SourceType::Text);
    }
}
